spring:
  application:
    name: jacory-space-api

  datasource:
    url: jdbc:mysql://localhost:3306/campus_life?useSSL=false&serverTimezone=UTC
    username: root
    password: Jinchengyue1124@
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 6666

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.campuslifebackend.domain.po
  configuration:
    map-underscore-to-camel-case: true

wx:
  appid: 你的微信小程序appid
  secret: 你的微信小程序secret

jwt:
  secret: Z9I9JMPDfXeZJZ9UeHD+aKHvu6egHPbP8sfeyEjJatg=